# Generated by Django 3.2.18 on 2023-03-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='percentage',
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
