# Generated by Django 3.2.18 on 2023-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230326_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='message',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
