# Generated by Django 3.2.18 on 2023-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230326_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='message',
        ),
    ]
