# Generated by Django 3.2.18 on 2023-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_student_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='message',
            field=models.CharField(blank=True, default='Unknown', max_length=250),
        ),
    ]
