# Generated by Django 3.2.18 on 2023-03-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_student_message'),
    ]

    operations = [
    ]
