# Generated by Django 3.2.18 on 2023-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230326_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
